'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PMPE.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Abandon the game?.
        '''</summary>
        Friend ReadOnly Property AbandonGame() As String
            Get
                Return ResourceManager.GetString("AbandonGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The first version of this game was created in 2010 with Visual Studio 2005. 
        '''
        '''This version is a full refactor of the first, done in 2022 with Visual Studio 2022.
        '''
        '''
        '''The sounds are free to use for non-commercial applications.
        '''
        '''Pictionary and Pictionary Mania! are trademarks of Mattel, Inc. This program was created as a programming exercise and it does not reproduce the original game&apos;s full mechanics. I don&apos;t make any money out of it and it can&apos;t be sold. 
        '''
        '''The background image is based on a picture o [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property AboutNotice() As String
            Get
                Return ResourceManager.GetString("AboutNotice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property allinthewrist_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("allinthewrist_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property app_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("app_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property blip_sound() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("blip_sound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property classic_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("classic_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting a new game will reload all databases, and any words that have already appeared may do so again. 
        '''
        '''Continue?.
        '''</summary>
        Friend ReadOnly Property ConfirmReload() As String
            Get
                Return ResourceManager.GetString("ConfirmReload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property directadraw_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("directadraw_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property drawback_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("drawback_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eng_flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eng_flag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fin_flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fin_flag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property gong_sound() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("gong_sound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ita_flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ita_flag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This word is last one left! Once you&apos;re done, press &quot;New game&quot; to start over if you wish..
        '''</summary>
        Friend ReadOnly Property LastWordWarning() As String
            Get
                Return ResourceManager.GetString("LastWordWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loader_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loader_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''No database is available, so the game can&apos;t be played. Either restore a backup of the databases or reinstall the application to solve the problem..
        '''</summary>
        Friend ReadOnly Property MissingDatabaseAll() As String
            Get
                Return ResourceManager.GetString("MissingDatabaseAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''Corresponding categories aren&apos;t playable and have been disabled. Remaining categories can still be played. Either restore a backup of the databases or reinstall the application to solve the problem..
        '''</summary>
        Friend ReadOnly Property MissingDatabaseSome() As String
            Get
                Return ResourceManager.GetString("MissingDatabaseSome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The following databases are missing or unaccessible:
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property MissingDatabaseStub() As String
            Get
                Return ResourceManager.GetString("MissingDatabaseStub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property peopleputty_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("peopleputty_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property pictionary() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("pictionary", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settings_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shuteye_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shuteye_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property start_sound() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("start_sound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property tick_sound() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("tick_sound", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
